chore: DRY for schema composition
influxdata/flux-lsp pull request #559
Opened 2022-08-12 17:09 UTC by wiedld

### In chain of PRs:
1. composition query analyzer
   * https://github.com/influxdata/flux-lsp/pull/551
2. composition query builder
   * https://github.com/influxdata/flux-lsp/pull/554
3. filter with multiple predicates in logical expression
   * https://github.com/influxdata/flux-lsp/pull/555
4. `add_field()`
   * https://github.com/influxdata/flux-lsp/pull/556
5. `add_tag_values()`
   * https://github.com/influxdata/flux-lsp/pull/557
6. `add_tag()`
   * https://github.com/influxdata/flux-lsp/pull/558
7. DRY into `remove_previous()` method
   * **THIS PR**

### Goal for this PR:
Now that we have demonstrated the exact same code everywhere, start DRY on the common code pattern.

This PR is intentionally the last in the PR daisy chain, because there is **alot more common code** which we could extract...but I don't want to push the limits without insight from the rest of the team. Once peeps are back, we can expand more on this PR.

2022-08-15 20:48 UTC, appletreeisyellow approved these changes
Thanks for cleaning up!

2022-08-22 20:09 UTC, rockstar requested changes
Please let's not do any refactoring until we've delivered a stable feature. The tests enforce our behavior, so we can refactor later without consequence. "YAGNI before DRY," in other words.

2022-08-23 01:20 UTC, wiedld commented
> Please let's not do any refactoring until we've delivered a stable feature. The tests enforce our behavior, so we can refactor later without consequence. "YAGNI before DRY," in other words.

Converted back to draft. Will re-assess in another two weeks.

2022-09-29 22:15 UTC, wiedld commented
Looks like we are going in an entirely different direction now. Closing this PR.

2022-09-29 22:15 UTC, closed without merging